all:
  children:
    masters:
      hosts:
        master-01:
          ansible_host: 10.0.1.10
        # master-02:
        #   ansible_host: 10.0.1.11
        # master-03:
        #   ansible_host: 10.0.1.12
    workers:
      hosts:
        worker-01:
          ansible_host: 10.0.2.10
        # worker-02:
        #   ansible_host: 10.0.2.11
        # worker-03:
        #   ansible_host: 10.0.2.12
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: ubuntu
