---
rke2_version: v1.31.4+rke2r1
rke2_channel: stable
rke2_server_ip: "{{ hostvars[groups['masters'][0]]['ansible_host'] }}"
rke2_token: "<CHANGE_ME>"
rke2_data_dir: /var/lib/rancher/rke2
rke2_config_dir: /etc/rancher/rke2
rke2_server_port: 9345
rke2_api_port: 6443
rke2_install_script_url: https://get.rke2.io
