//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

func (in *AffinitySpec) DeepCopyInto(out *AffinitySpec) {
	*out = *in
	if in.NodeAffinity != nil {
		in, out := &in.NodeAffinity, &out.NodeAffinity
		*out = new(apiextensionsv1.JSON)
		(*in).DeepCopyInto(*out)
	}
	if in.PodAffinity != nil {
		in, out := &in.PodAffinity, &out.PodAffinity
		*out = new(apiextensionsv1.JSON)
		(*in).DeepCopyInto(*out)
	}
	if in.PodAntiAffinity != nil {
		in, out := &in.PodAntiAffinity, &out.PodAntiAffinity
		*out = new(apiextensionsv1.JSON)
		(*in).DeepCopyInto(*out)
	}
}

func (in *AffinitySpec) DeepCopy() *AffinitySpec {
	if in == nil {
		return nil
	}
	out := new(AffinitySpec)
	in.DeepCopyInto(out)
	return out
}

func (in *AgentK8sSpec) DeepCopyInto(out *AgentK8sSpec) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(ResourceSpec)
		(*in).DeepCopyInto(*out)
	}
	in.Scheduling.DeepCopyInto(&out.Scheduling)
}

func (in *AgentK8sSpec) DeepCopy() *AgentK8sSpec {
	if in == nil {
		return nil
	}
	out := new(AgentK8sSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *AgentNodeSpec) DeepCopyInto(out *AgentNodeSpec) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(ResourceSpec)
		(*in).DeepCopyInto(*out)
	}
	in.Scheduling.DeepCopyInto(&out.Scheduling)
}

func (in *AgentNodeSpec) DeepCopy() *AgentNodeSpec {
	if in == nil {
		return nil
	}
	out := new(AgentNodeSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *AgentSpec) DeepCopyInto(out *AgentSpec) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(ResourceSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]ContainerPortSpec, len(*in))
		copy(*out, *in)
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]EnvVar, len(*in))
		copy(*out, *in)
	}
	in.Node.DeepCopyInto(&out.Node)
	in.Kubernetes.DeepCopyInto(&out.Kubernetes)
	in.Scheduling.DeepCopyInto(&out.Scheduling)
	in.ServiceAccount.DeepCopyInto(&out.ServiceAccount)
}

func (in *AgentSpec) DeepCopy() *AgentSpec {
	if in == nil {
		return nil
	}
	out := new(AgentSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *AutoscalingSpec) DeepCopyInto(out *AutoscalingSpec) {
	*out = *in
}

func (in *AutoscalingSpec) DeepCopy() *AutoscalingSpec {
	if in == nil {
		return nil
	}
	out := new(AutoscalingSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *BackendSpec) DeepCopyInto(out *BackendSpec) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(ResourceSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]ContainerPortSpec, len(*in))
		copy(*out, *in)
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]EnvVar, len(*in))
		copy(*out, *in)
	}
	in.Scheduling.DeepCopyInto(&out.Scheduling)
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(ComponentServiceSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Ingress != nil {
		in, out := &in.Ingress, &out.Ingress
		*out = new(ComponentIngressSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Autoscaling != nil {
		in, out := &in.Autoscaling, &out.Autoscaling
		*out = new(AutoscalingSpec)
		**out = **in
	}
	in.ServiceAccount.DeepCopyInto(&out.ServiceAccount)
}

func (in *BackendSpec) DeepCopy() *BackendSpec {
	if in == nil {
		return nil
	}
	out := new(BackendSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *CollectorSpec) DeepCopyInto(out *CollectorSpec) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(ResourceSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Persistence != nil {
		in, out := &in.Persistence, &out.Persistence
		*out = new(PersistenceSpec)
		**out = **in
	}
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]ContainerPortSpec, len(*in))
		copy(*out, *in)
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]EnvVar, len(*in))
		copy(*out, *in)
	}
	in.Scheduling.DeepCopyInto(&out.Scheduling)
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(ComponentServiceSpec)
		(*in).DeepCopyInto(*out)
	}
	in.ServiceAccount.DeepCopyInto(&out.ServiceAccount)
	in.Security.DeepCopyInto(&out.Security)
}

func (in *CollectorSpec) DeepCopy() *CollectorSpec {
	if in == nil {
		return nil
	}
	out := new(CollectorSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *ComponentIngressSpec) DeepCopyInto(out *ComponentIngressSpec) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Paths != nil {
		in, out := &in.Paths, &out.Paths
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

func (in *ComponentIngressSpec) DeepCopy() *ComponentIngressSpec {
	if in == nil {
		return nil
	}
	out := new(ComponentIngressSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *ComponentServiceSpec) DeepCopyInto(out *ComponentServiceSpec) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

func (in *ComponentServiceSpec) DeepCopy() *ComponentServiceSpec {
	if in == nil {
		return nil
	}
	out := new(ComponentServiceSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *ComponentStatus) DeepCopyInto(out *ComponentStatus) {
	*out = *in
}

func (in *ComponentStatus) DeepCopy() *ComponentStatus {
	if in == nil {
		return nil
	}
	out := new(ComponentStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *ContainerPortSpec) DeepCopyInto(out *ContainerPortSpec) {
	*out = *in
}

func (in *ContainerPortSpec) DeepCopy() *ContainerPortSpec {
	if in == nil {
		return nil
	}
	out := new(ContainerPortSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *CoreResource) DeepCopyInto(out *CoreResource) {
	*out = *in
}

func (in *CoreResource) DeepCopy() *CoreResource {
	if in == nil {
		return nil
	}
	out := new(CoreResource)
	in.DeepCopyInto(out)
	return out
}

func (in *DatabaseSpec) DeepCopyInto(out *DatabaseSpec) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(ResourceSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Persistence != nil {
		in, out := &in.Persistence, &out.Persistence
		*out = new(PersistenceSpec)
		**out = **in
	}
	if in.Credentials != nil {
		in, out := &in.Credentials, &out.Credentials
		*out = new(SecretRef)
		**out = **in
	}
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]ContainerPortSpec, len(*in))
		copy(*out, *in)
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]EnvVar, len(*in))
		copy(*out, *in)
	}
	in.Scheduling.DeepCopyInto(&out.Scheduling)
}

func (in *DatabaseSpec) DeepCopy() *DatabaseSpec {
	if in == nil {
		return nil
	}
	out := new(DatabaseSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *EnvVar) DeepCopyInto(out *EnvVar) {
	*out = *in
}

func (in *EnvVar) DeepCopy() *EnvVar {
	if in == nil {
		return nil
	}
	out := new(EnvVar)
	in.DeepCopyInto(out)
	return out
}

func (in *FrontendSpec) DeepCopyInto(out *FrontendSpec) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(ResourceSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]ContainerPortSpec, len(*in))
		copy(*out, *in)
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]EnvVar, len(*in))
		copy(*out, *in)
	}
	in.Scheduling.DeepCopyInto(&out.Scheduling)
	if in.Ingress != nil {
		in, out := &in.Ingress, &out.Ingress
		*out = new(ComponentIngressSpec)
		(*in).DeepCopyInto(*out)
	}
}

func (in *FrontendSpec) DeepCopy() *FrontendSpec {
	if in == nil {
		return nil
	}
	out := new(FrontendSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *IngressHost) DeepCopyInto(out *IngressHost) {
	*out = *in
	if in.Paths != nil {
		in, out := &in.Paths, &out.Paths
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

func (in *IngressHost) DeepCopy() *IngressHost {
	if in == nil {
		return nil
	}
	out := new(IngressHost)
	in.DeepCopyInto(out)
	return out
}

func (in *IngressSpec) DeepCopyInto(out *IngressSpec) {
	*out = *in
	if in.Hosts != nil {
		in, out := &in.Hosts, &out.Hosts
		*out = make([]IngressHost, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *IngressSpec) DeepCopy() *IngressSpec {
	if in == nil {
		return nil
	}
	out := new(IngressSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *JetStreamSpec) DeepCopyInto(out *JetStreamSpec) {
	*out = *in
}

func (in *JetStreamSpec) DeepCopy() *JetStreamSpec {
	if in == nil {
		return nil
	}
	out := new(JetStreamSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *NATSSpec) DeepCopyInto(out *NATSSpec) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(ResourceSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Persistence != nil {
		in, out := &in.Persistence, &out.Persistence
		*out = new(PersistenceSpec)
		**out = **in
	}
	if in.JetStream != nil {
		in, out := &in.JetStream, &out.JetStream
		*out = new(JetStreamSpec)
		**out = **in
	}
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]ContainerPortSpec, len(*in))
		copy(*out, *in)
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]EnvVar, len(*in))
		copy(*out, *in)
	}
	in.Scheduling.DeepCopyInto(&out.Scheduling)
}

func (in *NATSSpec) DeepCopy() *NATSSpec {
	if in == nil {
		return nil
	}
	out := new(NATSSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *PersistenceSpec) DeepCopyInto(out *PersistenceSpec) {
	*out = *in
}

func (in *PersistenceSpec) DeepCopy() *PersistenceSpec {
	if in == nil {
		return nil
	}
	out := new(PersistenceSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *RedisSpec) DeepCopyInto(out *RedisSpec) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(ResourceSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Persistence != nil {
		in, out := &in.Persistence, &out.Persistence
		*out = new(PersistenceSpec)
		**out = **in
	}
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]ContainerPortSpec, len(*in))
		copy(*out, *in)
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]EnvVar, len(*in))
		copy(*out, *in)
	}
	in.Scheduling.DeepCopyInto(&out.Scheduling)
}

func (in *RedisSpec) DeepCopy() *RedisSpec {
	if in == nil {
		return nil
	}
	out := new(RedisSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *ResourceSpec) DeepCopyInto(out *ResourceSpec) {
	*out = *in
	out.Requests = in.Requests
	out.Limits = in.Limits
}

func (in *ResourceSpec) DeepCopy() *ResourceSpec {
	if in == nil {
		return nil
	}
	out := new(ResourceSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *SchedulingSpec) DeepCopyInto(out *SchedulingSpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]TolerationSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TopologySpreadConstraints != nil {
		in, out := &in.TopologySpreadConstraints, &out.TopologySpreadConstraints
		*out = make([]TopologySpreadConstraintSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(AffinitySpec)
		(*in).DeepCopyInto(*out)
	}
}

func (in *SchedulingSpec) DeepCopy() *SchedulingSpec {
	if in == nil {
		return nil
	}
	out := new(SchedulingSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *SecretRef) DeepCopyInto(out *SecretRef) {
	*out = *in
}

func (in *SecretRef) DeepCopy() *SecretRef {
	if in == nil {
		return nil
	}
	out := new(SecretRef)
	in.DeepCopyInto(out)
	return out
}

func (in *SecretsSpec) DeepCopyInto(out *SecretsSpec) {
	*out = *in
	out.Backend = in.Backend
	out.Agent = in.Agent
	out.Collector = in.Collector
	out.Database = in.Database
}

func (in *SecretsSpec) DeepCopy() *SecretsSpec {
	if in == nil {
		return nil
	}
	out := new(SecretsSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *SecurityContextSpec) DeepCopyInto(out *SecurityContextSpec) {
	*out = *in
	if in.RunAsUser != nil {
		in, out := &in.RunAsUser, &out.RunAsUser
		*out = new(int64)
		**out = **in
	}
	if in.RunAsGroup != nil {
		in, out := &in.RunAsGroup, &out.RunAsGroup
		*out = new(int64)
		**out = **in
	}
	if in.RunAsNonRoot != nil {
		in, out := &in.RunAsNonRoot, &out.RunAsNonRoot
		*out = new(bool)
		**out = **in
	}
	if in.ReadOnlyRootFilesystem != nil {
		in, out := &in.ReadOnlyRootFilesystem, &out.ReadOnlyRootFilesystem
		*out = new(bool)
		**out = **in
	}
	if in.AllowPrivilegeEscalation != nil {
		in, out := &in.AllowPrivilegeEscalation, &out.AllowPrivilegeEscalation
		*out = new(bool)
		**out = **in
	}
	if in.DropCapabilities != nil {
		in, out := &in.DropCapabilities, &out.DropCapabilities
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AddCapabilities != nil {
		in, out := &in.AddCapabilities, &out.AddCapabilities
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

func (in *SecurityContextSpec) DeepCopy() *SecurityContextSpec {
	if in == nil {
		return nil
	}
	out := new(SecurityContextSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *ServiceAccountSpec) DeepCopyInto(out *ServiceAccountSpec) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

func (in *ServiceAccountSpec) DeepCopy() *ServiceAccountSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceAccountSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *TelemetryFlow) DeepCopyInto(out *TelemetryFlow) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *TelemetryFlow) DeepCopy() *TelemetryFlow {
	if in == nil {
		return nil
	}
	out := new(TelemetryFlow)
	in.DeepCopyInto(out)
	return out
}

func (in *TelemetryFlow) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *TelemetryFlowList) DeepCopyInto(out *TelemetryFlowList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TelemetryFlow, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *TelemetryFlowList) DeepCopy() *TelemetryFlowList {
	if in == nil {
		return nil
	}
	out := new(TelemetryFlowList)
	in.DeepCopyInto(out)
	return out
}

func (in *TelemetryFlowList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *TelemetryFlowSpec) DeepCopyInto(out *TelemetryFlowSpec) {
	*out = *in
	in.Backend.DeepCopyInto(&out.Backend)
	in.Frontend.DeepCopyInto(&out.Frontend)
	in.Collector.DeepCopyInto(&out.Collector)
	in.Agent.DeepCopyInto(&out.Agent)
	in.PostgreSQL.DeepCopyInto(&out.PostgreSQL)
	in.ClickHouse.DeepCopyInto(&out.ClickHouse)
	in.Redis.DeepCopyInto(&out.Redis)
	in.BullMQRedis.DeepCopyInto(&out.BullMQRedis)
	in.NATS.DeepCopyInto(&out.NATS)
	in.Ingress.DeepCopyInto(&out.Ingress)
	in.Secrets.DeepCopyInto(&out.Secrets)
}

func (in *TelemetryFlowSpec) DeepCopy() *TelemetryFlowSpec {
	if in == nil {
		return nil
	}
	out := new(TelemetryFlowSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *TelemetryFlowStatus) DeepCopyInto(out *TelemetryFlowStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ComponentStatuses != nil {
		in, out := &in.ComponentStatuses, &out.ComponentStatuses
		*out = make(map[string]ComponentStatus, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

func (in *TelemetryFlowStatus) DeepCopy() *TelemetryFlowStatus {
	if in == nil {
		return nil
	}
	out := new(TelemetryFlowStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *TolerationSpec) DeepCopyInto(out *TolerationSpec) {
	*out = *in
	if in.TolerationSeconds != nil {
		in, out := &in.TolerationSeconds, &out.TolerationSeconds
		*out = new(int64)
		**out = **in
	}
}

func (in *TolerationSpec) DeepCopy() *TolerationSpec {
	if in == nil {
		return nil
	}
	out := new(TolerationSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *TopologySpreadConstraintSpec) DeepCopyInto(out *TopologySpreadConstraintSpec) {
	*out = *in
	if in.LabelSelector != nil {
		in, out := &in.LabelSelector, &out.LabelSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

func (in *TopologySpreadConstraintSpec) DeepCopy() *TopologySpreadConstraintSpec {
	if in == nil {
		return nil
	}
	out := new(TopologySpreadConstraintSpec)
	in.DeepCopyInto(out)
	return out
}
