---
- name: Restart tfo clickhouse
  community.docker.docker_compose_v2:
    project_src: "{{ tfo_platform_install_dir }}"
    files:
      - docker-compose.clickhouse.yml
    project_name: "{{ tfo_platform_compose_project_name }}"
    state: present
    recreate: always
  listen: restart tfo clickhouse
