{{- if .Values.secrets.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.tfoBackend.name }}
  namespace: {{ include "telemetryflow.namespace" . }}
  labels:
    {{- include "telemetryflow.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
type: Opaque
data:
  {{- range $key, $value := .Values.secrets.tfoBackend.data }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.tfoAgent.name }}
  namespace: {{ include "telemetryflow.namespace" . }}
  labels:
    {{- include "telemetryflow.labels" . | nindent 4 }}
    app.kubernetes.io/component: agent
type: Opaque
data:
  {{- range $key, $value := .Values.secrets.tfoAgent.data }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.redis.name }}
  namespace: {{ include "telemetryflow.namespace" . }}
  labels:
    {{- include "telemetryflow.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
type: Opaque
data:
  {{- range $key, $value := .Values.secrets.redis.data }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.postgresql.name }}
  namespace: {{ include "telemetryflow.namespace" . }}
  labels:
    {{- include "telemetryflow.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
type: Opaque
data:
  {{- range $key, $value := .Values.secrets.postgresql.data }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.clickhouse.name }}
  namespace: {{ include "telemetryflow.namespace" . }}
  labels:
    {{- include "telemetryflow.labels" . | nindent 4 }}
    app.kubernetes.io/component: clickhouse
type: Opaque
data:
  {{- range $key, $value := .Values.secrets.clickhouse.data }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.nats.name }}
  namespace: {{ include "telemetryflow.namespace" . }}
  labels:
    {{- include "telemetryflow.labels" . | nindent 4 }}
    app.kubernetes.io/component: nats
type: Opaque
data:
  {{- range $key, $value := .Values.secrets.nats.data }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- if .Values.secrets.valkey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.valkey.name }}
  namespace: {{ include "telemetryflow.namespace" . }}
  labels:
    {{- include "telemetryflow.labels" . | nindent 4 }}
    app.kubernetes.io/component: valkey
type: Opaque
data:
  {{- range $key, $value := .Values.secrets.valkey.data }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}
